#!/usr/bin/env bash

cat schema.sql | sqlite3 blog.db

mkdir content
cd content

mkdir posts images drafts
git init
cp ../githooks/post-receive .git/hooks
git config receive.denyCurrentBranch updateInstead
